### ISSUE TITLE
access to "dataset"

### ISSUE THREAD

**Issue by alusiani** [inspirehep/rest-api-doc#26]
Hi,

I would like to use the API to get the *dataset* information, a link to a [HEPData](https://www.hepdata.net/) record that exists for a subset og inspirehep records. Is that possible? A test on [https://inspirehep.net/api/literature/1392895](https://inspirehep.net/api/literature/1392895) does not reveal this content. Would it be possible to include this information in the JSON text that is returned? In this case it should return the link [https://www.hepdata.net/record/ins1392895](https://www.hepdata.net/record/ins1392895).

Best regards,

Alberto Lusiani

**Comment by michamos** [comment]
Hi @alusiani, the link itself is not present in the metadata, but the information is present under `external_system_identifiers`. When there's a corresponding HEPData dataset, there will be an entry with `schema` set to `HEPDATA` and the record ID as a `value`. To reconstruct the URL, you need to prepend `https://www.hepdata.net/record/` to that value. I agree it's not super user friendly though.

**Comment by alusiani** [comment]
Hi,

thanks for the fast feedback!  The information then is indeed available, I missed it.  The present format is surely usable.

> Hi @alusiani, the link itself is not present in the metadata, but the information is present under `external_system_identifiers`. When there's a corresponding HEPData dataset, there will be an entry with `schema` set to `HEPData` and the record ID as a `value`. To reconstruct the URL, you need to prepend `https://www.hepdata.net/record/ins` to that value. I agree it's not super user friendly though.
