### ISSUE TITLE
CV Format returns blank html body

### ISSUE THREAD

**Issue by jxi24** [inspirehep/rest-api-doc#29]
According to the documentation, there is now the option to obtain an html cv format for a query. However, when I attempt it, I obtain an html document that just has a blank body tag.

For example calling the URL: 
`https://inspirehep.net/api/literature?format=cv&q=a%20Joshua.Isaacson.1`

returns:

```
<!DOCTYPE html>
<html>
<body>
  
  
  
  
  
  
  
  
  
  
</body>
</html>
```

Is this the correct way to access this information?

**Comment by michamos** [comment]
This has been fixed, so I'm closing the issue.
