### ISSUE TITLE
Mismatch between API and webpage

### ISSUE THREAD

**Issue by selvaggi** [inspirehep/rest-api-doc#31]
Hello,

the following API query:

https://inspirehep.net/api/literature?sort=mostcited&size=25&page=1&q=a%20M.Selvaggi.1

yields a different result than the following page:

https://inspirehep.net/authors/1039590

in particular the first most cited paper is missing in the API query. Am I using the wrong syntax?

**Comment by michamos** [comment]
Hi Michele,

Thanks for reporting this. The syntax was correct but we had a consistency bug that has now been resolved: https://inspirehep.net/api/literature?sort=mostcited&size=25&page=1&q=a%20Michele.Selvaggi.1.
