### ISSUE TITLE
Getting Inspire ID and DOI from an API record

### ISSUE THREAD

**Issue by agbuckley** [inspirehep/rest-api-doc#6]
I am updating a tool that uses the old Inspire API XML output to retrieve metadata including the Inspire ID, arXiv ID, and DOI, from searches using any of the same as keys. But in the new format, the Inspire ID and DOI don't seem to exist in the JSON output:

- the `id` is only the Inspire ID if the `api/literature` URL structure was used, but is the arXiv or DOI identifier if they were used as the search key;
- DOIs are listed for the citations, but not for the record itself as far as I can tell.

Could this canonical information be added to the JSON output... or did I miss something?! Thanks.

**Comment by michamos** [comment]
The `id` field is just a shortcut, all the metadata is also available under `metadata`:
* INSPIRE record ID is under `metadata.control_number`
* DOI (if present) under `metadata.dois`
* arXiv ID under `metadata.arxiv_eprints`.

You can find more information on the different fields available under `metadata` here: https://inspire-schemas.readthedocs.io/en/latest/schemas/hep.html.

**Comment by agbuckley** [comment]
I just found the DOIs one... not sure how I missed it. Thanks re. the `control_number`, I didn't guess that one!

**Comment by michamos** [comment]
I agree the name is not great, I'll try to clarify this in the docs.

**Comment by agbuckley** [comment]
Cheers!
