### ISSUE TITLE
Finding articles by old SPIRES ID code

### ISSUE THREAD

**Issue by agbuckley** [inspirehep/rest-api-doc#7]
I'm updating the Rivet toolkit helper programs to use the new API (they are currently pointing at old.inspirehep.net, which is not sustainable) and since old analyses in our collection -- from before Inspire existed -- are named with the old SPIRES database key, we ideally need to be able to query by this as well.

Digging in an example record, I found SPIRES IDs referenced in the `external_system_identifiers` list, e.g.
`{"schema":"SPIRES","value":"SPIRES-8924791"}`
Is this something that can also be searched on?

**Comment by michamos** [comment]
Yes, you can search on any field in `metadata`, as explained [here](https://github.com/inspirehep/rest-api-doc#search-query). In this case, you could use [`external_system_identifiers.value:SPIRES-8924791`](https://inspirehep.net/api/literature?q=external_system_identifiers.value:SPIRES-8924791).

**Comment by agbuckley** [comment]
Ah, excellent: I was hoping to use it as a unique key like the `doi`, `literature`, `arxiv` ones, but it's understandable that you don't want that up-front. I now have this working as a 2-stage search to get the Inspire ID, and then look it up like a "native" Inspire key. Thanks! Just one comment: the two levels of `hits` keys in the search result is a bit surprising, but not insurmountable.
